name: Giang N.Le
markdown: redcarpet
pygments: true
github: https://www.github.com/lengocgiang
about: I am a software engineer, forcus iOS. I'm using Objective-C and learning Swift for my project
urls:
    - text: github
      url: https://github.com/lengocgiang
    - text: email
      url: mailto:gianglengoc.hut@gmail.com
